# Generated by Django 3.1.13 on 2024-04-13 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20240413_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='returnn',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
