# Generated by Django 3.1.13 on 2024-04-13 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_season_returnn'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='classs',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.season'),
        ),
    ]
