# Generated by Django 3.1.13 on 2024-04-14 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20240413_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='color',
            new_name='typee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='design',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='season',
        ),
        migrations.AddField(
            model_name='order',
            name='amt',
            field=models.PositiveIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(default=django.utils.timezone.now, max_length=220),
            preserve_default=False,
        ),
    ]
