# Generated by Django 3.1.13 on 2024-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20240414_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amt',
            field=models.TextField(max_length=220),
        ),
    ]
