# Generated by Django 3.1.13 on 2024-04-14 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_order_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amt',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
