# Generated by Django 3.1.13 on 2024-04-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('rejected', 'Rejected')], default='complete', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approved', 'Approved'), ('complete', 'Complete')], max_length=10),
        ),
    ]
