# Generated by Django 3.1.13 on 2024-04-15 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20240414_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='interest',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenure',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('decline', 'Decline')], max_length=20),
        ),
    ]
