# Generated by Django 3.1.13 on 2024-04-15 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20240415_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='interest',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='tenure',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
