# Generated by Django 3.1.13 on 2024-04-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20240415_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.season'),
        ),
    ]
